import { StyleSheet } from 'react-native';

// Cores
export const CORES = {
  primaria: '#017BC8',
  secundaria: '#DAF1FF',
  texto: '#1E1E1E',
  textoClaro: '#F2F2F2',
  textoCinza: '#6D6D6D',
} as const;

// Fontes
const textoNormal = 'Montserrat_400Regular';
const textoMedio = 'Montserrat_500Medium';
const textoNegrito = 'Montserrat_700Bold';

export default StyleSheet.create({
  // Tela de Login
  loginBG: {
    height: '100%',
    padding: 35,
  },
  loginContainer: {
    justifyContent: 'center',
    marginTop: 50,
  },
  logoLogin: {
    width: 300,
    height: 70,
    marginTop: 120,
  },
  comentario: {
    fontSize: 15,
    fontFamily: textoNormal,
    color: CORES.textoCinza,
    marginTop: 30,
    marginBottom: 40,
  },
  negrito: {
    fontFamily: textoNegrito,
  },
  texto: {
    color: CORES.texto,
    fontFamily: textoMedio,
    fontSize: 14,
  },
  input: {
    marginVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderColor: '#b9b9b9',
    color: CORES.textoCinza,
    fontFamily: textoNormal,
  },
  botao: {
    padding: 15,
    backgroundColor: CORES.primaria,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 40,
  },
  textoBotao: {
    fontSize: 14,
    fontFamily: textoNormal,
    color: CORES.textoClaro,
  },
  contatoLogin: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 10,
    marginBottom: 30,
  },
  // Barra de Navegação
  tabBar: {
    backgroundColor: CORES.primaria,
    height: 60,
    borderTopWidth: 0,
    paddingTop: 9,
  },
  iconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeIconContainer: {
    backgroundColor: CORES.primaria,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -50,
    width: 65,
    height: 65,
    borderWidth: 5,
    borderColor: CORES.textoClaro,
  },
  // Tela Home
  container: {
    padding: 40,
    paddingTop: 70,
  },
  titulo: {
    fontFamily: textoMedio,
    color: CORES.primaria,
    letterSpacing: 3,
    fontSize: 22,
  },
  pontosContainer: {
    borderRadius: 10,
    backgroundColor: CORES.secundaria,
    marginVertical: 20,
    paddingBottom: 30,
    elevation: 10,
    marginTop: 30,
  },
  pontosHome: {
    backgroundColor: 'white',
    borderBottomRightRadius: 300,
    borderBottomLeftRadius: 300,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    alignItems: 'center',
    paddingVertical: 30,
    gap: 5,
  },
  pontosHomeTitulo: {
    fontFamily: textoMedio,
    color: CORES.primaria,
    fontSize: 20,
    letterSpacing: 3,
    textAlign: 'center',
    paddingHorizontal: 5,
  },
  lojaHome: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 15,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  subtitulo: {
    color: CORES.primaria,
    fontSize: 16,
    fontFamily: textoNormal,
  },
  link: {
    textDecorationLine: 'underline',
  },
  // Tela de Ranking
  cardRankingUser: {
    backgroundColor: CORES.textoClaro,
    width: '100%',
    flex: 1,
    marginTop: 20,
    alignItems: 'center',
    position: 'absolute',
    bottom: -40,
  },
  bolinhaRanking: {
    width: 7,
    height: 7,
    borderWidth: 1.5,
    borderColor: CORES.primaria,
    borderRadius: 10,
    marginBottom: 7,
  },
  posicaoRankingUser: {
    borderRadius: 12,
    paddingVertical: 50,
    paddingHorizontal: 160,
    borderWidth: 2,
    borderColor: CORES.primaria,
    position: 'relative',
  },
  circle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: CORES.primaria,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  numeroRanking: {
    color: CORES.textoClaro,
    fontSize: 18,
    fontFamily: textoNegrito,
    letterSpacing: 2,
  },
  infoRanking: {
    marginLeft: 15,
  },
  // bem gambiarra para fazer a estilização que eu quero :)
  bg: {
    backgroundColor: CORES.textoClaro,
    paddingHorizontal: 120,
    paddingVertical: 5,
    alignItems: 'center',
    top: 16,
    left: -90,
    flex: 1,
    flexDirection: 'row',
    position: 'absolute',
  },
  nomeRanking: {
    color: CORES.primaria,
    fontSize: 16,
    fontFamily: textoMedio,
    marginBottom: 3,
  },
  pontosRanking: {
    borderBottomWidth: 1,
    borderColor: CORES.primaria,
    width: 130,
    paddingBottom: 3,
  },
  // Quando o usuário estiver em primeiro lugar
  bolinhaRankingFirst: {
    width: 7,
    height: 7,
    borderWidth: 1.5,
    borderColor: '#099c4b',
    borderRadius: 10,
    marginBottom: 7,
  },
  posicaoRankingUserFirst: {
    borderRadius: 12,
    paddingVertical: 55,
    paddingHorizontal: 160,
    borderWidth: 2,
    borderColor: '#099c4b',
    position: 'relative',
  },
  circleFirst: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#099c4b',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  nomeRankingFirst: {
    color: '#099c4b',
    fontSize: 16,
    fontFamily: textoMedio,
    marginBottom: 3,
  },
  pontosRankingFirst: {
    borderBottomWidth: 1,
    borderColor: '#099c4b',
    width: 130,
    paddingBottom: 3,
  },
  // Filtros
  filtros: {
    marginTop: 30,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 70,
  },
  botaoFiltro: {
    backgroundColor: CORES.secundaria,
    borderRadius: 5,
    elevation: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  textoFiltro: {
    fontFamily: textoMedio,
    color: CORES.primaria,
    fontSize: 16,
    letterSpacing: 2,
  },
  botaoAtivo: {
    backgroundColor: CORES.primaria,
  },
  textoFiltroAtivo: {
    color: CORES.textoClaro,
  },
  cardRanking: {
    flex: 1,
    flexDirection: 'row',
    marginVertical: 20,
  },
  icone: {
    marginLeft: 80,
    marginTop: 15,
  },
  // Loja
  botaoComprar: {
    backgroundColor: CORES.primaria,
    borderRadius: 7,
    padding: 15,
    alignItems: 'center',
    marginTop: 20,
  },
  // Habitos
  pickerContainer: {
    marginVertical: 30,
  },
  picker: {
    paddingLeft: 10,
    alignItems: 'center',
    textAlign: 'center',
    fontFamily: textoMedio,
  },
  fotoContainer: {
    flex: 1,
    flexDirection: 'row',
    gap: 80,
    marginVertical: 50,
    alignItems: 'center',
    position: 'relative',
    right: 0,
  },
  foto: {
    width: 150,
    height: 120,
    borderRadius: 7,
    position: 'absolute',
    right: 0,
    elevation: 5,
  },
  cameraContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: CORES.primaria,
    borderRadius: 50,
    width: 100,
    height: 100,
    position: 'absolute',
    left: 10,
    elevation: 5,
  },
  cardTitulo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fotoCard: {
    width: '100%',
    borderRadius: 10,
    height: 200,
    marginTop: 10,
    elevation: 5,
  },
  // Perfil
  headerPerfil: {
    alignItems: 'center',
  },
  fotoPerfil: {
    width: 200,
    height: 200,
    borderRadius: 100,
    marginBottom: 20,
  },
  cardInfo: {
    borderWidth: 1,
    borderColor: CORES.primaria,
    borderRadius: 12,
    padding: 15,
    gap: 5,
    marginBottom: 15,
  },
  tituloInfo: {
    fontSize: 16,
    fontFamily: textoMedio,
    color: CORES.primaria,
  },
  acoesPerfil: {
    marginTop: 20,
    flex: 1,
    gap: 12,
  },
  botaoPerfil: {
    backgroundColor: CORES.primaria,
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: 'center',
  },
  // Card IoT
  cardIoT: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardIoTHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  iotStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  iotStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  iotStatusText: {
    fontSize: 12,
    fontFamily: 'Montserrat_500Medium',
  },
  iotInputRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  iotInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#b9b9b9',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: 'Montserrat_400Regular',
    fontSize: 13,
    color: CORES.texto,
  },
  iotBotaoConectar: {
    backgroundColor: CORES.primaria,
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  iotBotaoDesconectar: {
    backgroundColor: '#e74c3c',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  iotBotaoTexto: {
    color: 'white',
    fontFamily: 'Montserrat_500Medium',
    fontSize: 13,
  },
  iotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  iotMetrica: {
    backgroundColor: CORES.secundaria,
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
    width: '47%',
  },
  iotMetricaValor: {
    fontSize: 20,
    fontFamily: 'Montserrat_700Bold',
    color: CORES.primaria,
  },
  iotMetricaLabel: {
    fontSize: 11,
    fontFamily: 'Montserrat_400Regular',
    color: CORES.textoCinza,
    marginTop: 2,
    textAlign: 'center',
  },
  iotTimestamp: {
    fontSize: 11,
    fontFamily: 'Montserrat_400Regular',
    color: CORES.textoCinza,
    textAlign: 'right',
    marginTop: 10,
  },
  iotErro: {
    color: '#e74c3c',
    fontFamily: 'Montserrat_400Regular',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 4,
  },
});
